export const REGIONS = {
	"amazon.com.au": "Australia",
	// "amazon.com.br": "Brazil",
	"amazon.ca": "Canada",
	// "amazon.com.tr": "Turkey",
	"amazon.co.jp": "Japan",
	// "amazon.cn": "China",
	// "amazon.eg": "Egypt",
	// "amazon.fr": "France",
	// "amazon.de": "Germany",
	"amazon.in": "India",
	// "amazon.it": "Italy",
	// "amazon.com.mx": "Mexico",
	// "amazon.nl": "Netherlands",
	// "amazon.pl": "Poland",
	// "amazon.sa": "Saudi Arabia",
	// "amazon.sg": "Singapore",
	// "amazon.es": "Spain",
	// "amazon.se": "Sweden",
	// "amazon.ae": "United Arab Emirates",
	"amazon.co.uk": "United Kingdom",
	"amazon.com": "United States (default)",
};
